export interface IViaje {
  id_viaje: number;
  id_movreg: number;
  cve_ubicacion_origen: string;
  cve_ubicacion_destino: string;
  id_proyecto: number;
  nombre_cliente: string;
  nombre_corto_cliente: string;
  facturar_a: string;
  fec_carga: string;
  fec_descarga: string;
  fec_estimada: string | null;
  fec_custodia: string | null;
  id_tractor: number | null;
  num_tractor: string | null;
  empleado: string | null;
  id_cia_empleado: number | null;
  id_lineatras: number | null;
  lineatras: string | null;
  id_caja: number | null;
  num_caja: string | null;
  ind_tipocaja: string | null;
  temperatura: number | null;
  ind_circulo_servicio: string;
  ind_tipo: string;
  id_empleado: number | null;
  id_viaje_r: number | null;
  id_ruta: number | null;
  porcentaje_viaje: number | null;
  latitud_ultima_posicion: number | null;
  longitud_ultima_posicion: number | null;
  horas_destino: number | null;
  fec_estimada_posicion: string | null;
  fec_ultima_posicion: string | null;
  kilometros: string | null;
  horas: number | null;
  distancia_destino: number | null;
  estatus_factura: string;
  num_factura: string | null;
  serie_factura: string | null;
  usuario_factura: string | null;
  fec_factura: string | null;
  folio_fiscal: string | null;
  zona: string | null;
  detalle_mercancia: string | null;
  productos: string | null;
  setpoint: number | null;
  parada_intermedia: string | null;
  frontera_cruce: string | null;
  grupo_trabajo: string | null;
  ultima_posicion: string | null;
  flete: number | null;
  ind_moneda_flete: string | null;
  eta_calculado: string | null;
  eta_planeado: string | null;
  orden_compra: string | null;
  id_orden_compra: number | null;
  ind_estado: string;
  estado: string;
  lineatras_caja: string | null;
  lineatras_tractor: string | null;
  activo: number;
  hora_carga: string | null;
  hora_descarga: string | null;
}

export interface IResponseViaje {
  viajes: IViaje [];
  total_registros: number;
}